routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

/*
|--------------------------------------------------------------------------
| COMANDO: php artisan make:auth QUE CRIA ESSAS LINHAS ABAIXO! 
|--------------------------------------------------------------------------
*/
//CRIA UMAS QUANTAS ROTAS OCULTAS AQUI POR ESSA UNICA LINHA DE CODIGO!
Auth::routes();

//CRIA A ROTA P/ ABRIR A PAG HOME D SITE EXEMPLO D LARAVEL DEPOIS D LOGADO!
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/perfil/{id}', 'HomeController@perfil')->name('home.perfil');
Route::post('/home/{id}', 'HomeController@update');

//CRIA A ROTA P/ ABRIR A PAG HOME D SITE EXEMPLO D LARAVEL DEPOIS D LOGADO!
Route::get('/admin', 'AdminController@index')->name('admin.dashboard');
Route::get('/admin/login', 'Auth\AdminLoginController@index')->name('admin.login');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/admin/perfil/{id}', 'AdminController@perfil')->name('admin.perfil');
Route::post('/admin/{id}', 'AdminController@update');
Route::get('/admin/clientes', 'ClienteController@index');
//Route::get('/admin/clientesjson', 'ClienteController@indexjson');

//CRIA A ROTA P/ ABRIR A PAG DE LISTAGEM DE ANIMAIS CADASTRADOS
Route::get('/animais','AnimalController@index');
Route::resource('animais', 'AnimalController');
Route::post('insere','AnimalController@store')->name('insere');

/**Route::prefix('/admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@index')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
});**/

/** Route::get('admin/perfil', function(){*/

resources/views/admin-old.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard - Admin</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Voce esta logado como administrador!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/animaisCad.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <form method="POST" action="{{route('animais.store')}}"> 
    {!! csrf_field() !!}
    <h3 class="lead">Cadastrar animal pra doação</h3>   
    <br>
    
    <div class="row">
      <div class="form-group col-sm-12 col-md-6">
        <label for="nome">Nome</label>
        <input class="form-control" type="text" name="nome" id="nome" required>
      </div>
      <div class="form-group col-sm-12 col-md-6">
        <label for="raca">Raça</label>
        <input class="form-control" type="text" name="raca" id="raca" required>
      </div>
    </div>
    
    <div class="row">
        <div class="form-group col-sm-12 col-md-6">
          <label for="porte">Porte</label>
          <input class="form-control" type="text" name="porte" id="porte" required>
        </div>
        <div class="form-group col-sm-12 col-md-6">
          <label for="idade">Idade</label>
          <input class="form-control" type="text" name="idade" id="idade" required>
        </div>
      </div>

      <div class="row">
          <div class="form-group col-sm-12 col-md-6">
            <label for="temperamento">Temperamento</label>
            <input class="form-control" type="text" name="temperamento" id="temperamento" required>
          </div>
      </div>
      
      <div class="row">
        <div class="form-group col-sm-12">
          <label for="historico">Historico</label>
          <textarea class="form-control" name="historico" id="historico" cols="30" rows="10"></textarea>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-12 text-center align-center">
          <button class="btn btn-primary btn-lg" type="submit">Doar</button>
          <button class="white-text btn btn-warning btn-lg" type="reset">Limpar</button>
        </div>
      </div>
  </form>
</div>
@endsection

    

resources/views/animaisList.blade.php
@extends('layouts.app')

@section('title', 'Animais Cadastrados')

@section('content_header')
    <h1>Animais Cadastrados</h1>
@endsection

@section('content')

@if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>  
@endif

<table class="table table-striped">
  <tr>
    <th> Id </th>
    <th> Tipo </th>
    <th> Raça </th>
    <th> Porte </th>
    <th> Idade </th>
    <th> Histórico </th>
    <th> Temperamento </th>    
  </tr>  
@forelse($animals  as $a)
  <tr>
    <td> {{$a->id}} </td>
    <td> {{$a->tipo}} </td>
    <td> {{$a->raca}} </td>
    <td> {{$a->porte}} </td>
    <td> {{$a->idade}} </td>
    <td> {{$a->historico}} </td>
    <td> {{$a->temperamento}} </td>
    
  </tr>
@empty
  <tr><td colspan=8> Não existem clientes Cadastrados No sistema </td></tr>
@endforelse
</table>
@endsection

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection

resources/views/clientes.blade.php
@extends('layouts.dashboard')
    <!-- FIM DO MENU LATERAL ESQUERDO -->
@section('conteudo')
        <div class="page-wrapper">                     
            <div class="page-breadcrumb">
                <div class="row align-items-center">
                    <div class="col-5">
                        <h4 class="page-title">CLIENTES</h4>
                        <div class="d-flex align-items-center">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item active" aria-current="page"><a href="/admin">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Clientes</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                    <div class="col-7">
                        <div class="text-right upgrade-btn">
                            <a href="#" class="btn btn-success text-white"><i class="fa fa-plus-square"></i> NOVO CLIENTE</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
            <div class="row">                  
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">                             
                                <div class="d-md-flex align-items-center">
                                    <div>
                                        <h4 class="card-title">LISTA DOS CLIENTES ATIVOS</h4>
                                        <h5 class="card-subtitle">Exebindo {{$clientes->count()}} 
                                            clientes de {{$clientes->total()}} 
                                            ({{$clientes->firstItem()}} a {{$clientes->lastItem()}}).</h5>
                                    </div>
                                    <div class="ml-auto">
                                        <div class="dl">
                                            <select class="custom-select">
                                                <option value="0" selected>Monthly</option>
                                                <option value="1">Daily</option>
                                                <option value="2">Weekly</option>
                                                <option value="3">Yearly</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>                               
                            </div>
                            <div class="table-responsive users">

   
                                  
                                    
                                    @include('componentes.tabela-clientes')                                  
                                                                     
                               
                                
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-md-flex align-items-center">
                                    <div>
                                        <h4 class="card-title">Sales Summary</h4>
                                        <h5 class="card-subtitle">Overview of Latest Month</h5>
                                    </div>
                                    <div class="ml-auto d-flex no-block align-items-center">
                                        <ul class="list-inline font-12 dl m-r-15 m-b-0">
                                            <li class="list-inline-item text-info"><i class="fa fa-circle"></i> Iphone</li>
                                            <li class="list-inline-item text-primary"><i class="fa fa-circle"></i> Ipad</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="row">                                    
                                    <div class="col-lg-12">
                                        <div class="campaign ct-charts"></div>
                                    </div>                                
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Feeds</h4>
                                <div class="feed-widget">
                                    <ul class="list-style-none feed-body m-0 p-b-20">
                                        <li class="feed-item">
                                            <div class="feed-icon bg-info"><i class="far fa-bell"></i></div> You have 4 pending tasks. <span class="ml-auto font-12 text-muted">Just Now</span></li>
                                        <li class="feed-item">
                                            <div class="feed-icon bg-success"><i class="ti-server"></i></div> Server #1 overloaded.<span class="ml-auto font-12 text-muted">2 Hours ago</span></li>
                                        <li class="feed-item">
                                            <div class="feed-icon bg-warning"><i class="ti-shopping-cart"></i></div> New order received.<span class="ml-auto font-12 text-muted">31 May</span></li>
                                        <li class="feed-item">
                                            <div class="feed-icon bg-danger"><i class="ti-user"></i></div> New user registered.<span class="ml-auto font-12 text-muted">30 May</span></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>         
        </div>
     
    
        @endsection

resources/views/home-laravel.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard usuario</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Voce esta logado como usuario!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection